server:
  port: 8090
  context-path:


zz:
  name: zhang
  age: 24

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10

  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      #去掉thymeleaf的严格的模板校验
      mode: LEGACYHTML5

  jpa:
      properties:
        hibernate:
          hbm2ddl:
            auto: update
      show-sql: true
#      database-platform: org.hibernate.dialect.H2Dialect

  redis:
      host: 10.6.4.154
      password: foobared
      port: 6379
      database: 4
      lettuce:
        pool:
          maxIdle: 50
          minIdle: 1
          maxActive: 50

mybatis:
  mapperLocations: classpath*:com/dao/*Mapper.xml
  typeAliasesPackage: com.entity